### ISSUE TITLE
Copy object path error

### ISSUE THREAD

**Issue by daledude** [belaviyo/json-beautifier#10]
Brave Version 1.28.83 Chromium: 92.0.4515.93 (Official Build) beta (64-bit)
json-beautifier: v0.3.0

So far very nice extension. When I click the copy object path this error is produced in console and nothing is copied:

```
inject.js:86 Uncaught TypeError: Cannot read property 'writeText' of undefined
    at Object.click (inject.js:86)
    at HTMLButtonElement.button.onclick (jsoneditor.js:181)
click @ inject.js:86
button.onclick @ jsoneditor.js:181
```

**Comment by belaviyo** [comment]
Is this happening on all websites? This extension uses the standard API;

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

**Comment by daledude** [comment]
Looks like HTTPS is required for copy to clipboard which I wasn't using. I'll figure a work around on my end. Thanks @belaviyo .
https://github.com/Glimesh/glimesh.tv/issues/496
