### ISSUE TITLE
Please add options page for 0.3.7 BigNumber behavior

### ISSUE THREAD

**Issue by warbaby** [belaviyo/json-beautifier#15]
First thanks for your great plugin. But my main usage scienario is "format json html response, and copy whole or part of the response". But he changes in 0.3.7 make this not so convenient.

I know it's to solve the #14 issue. But developers should always be ware that numbers exceed 2^53 are not safe in json. They should find their own way to solve the problem (by changing big number to string or limiting numbers output to 2^53 in design), not by a json beautifier plugin.

At least, please add an option page to change useNativeBigInt, or make BigNumber only effects numbers bigger than 2^53 (not by length>15).

Thanks a lot.

**Comment by belaviyo** [comment]
> copy whole or part of the response

How do you perform the copy? The extension is supposed to copy the BigInts correctly without being wrapped in an object.

**Comment by belaviyo** [comment]
btw, I added a new option to the right-click context menu to turn the conversion off.

**Comment by warbaby** [comment]
> > copy whole or part of the response
> 
> How do you perform the copy? The extension is supposed to copy the BigInts correctly without being wrapped in an object.

Oh, I see in the tree mode, if I use the sidebar copy menu, the big numbers are unwrapped.
I was saying that in code mode, "select text in the edit pane, and press Ctrl+C"...

Thank you for the new option, that's enough :)
