### ISSUE TITLE
application/json content type not activating extension in edge

### ISSUE THREAD

**Issue by ksp-jjensen** [belaviyo/json-beautifier#18]
I'm on `116.0.1938.54` of edge (win 11 x64). After a recent browser update I've been able unable to have `application/json` pages rendered. I've changed the header to be  `content-type: text/plain` and everything works as expected.

**Comment by belaviyo** [comment]
Please wait for the `0.4.1` release and report if it is fixed.

**Comment by ksp-jjensen** [comment]
Right as rain. Thanks! (fixed)
