### ISSUE TITLE
Use BigInt When Parsing JSON

### ISSUE THREAD

**Issue by HanYaodong** [belaviyo/json-beautifier#21]
Large numbers in json is getting converted to int and loosing precision. We can probably use BigInt for better compatibility.

**Comment by belaviyo** [comment]
Bigint functionality is already supported into the extension. You can find an example of its usage on the default page, accessible by clicking the action button. If you've encountered a specific instance where the parser isn't working correctly with Bigint, please share a sample.

**Comment by HanYaodong** [comment]
What I mean is all integer numbers should be parsed as BigInt to preserve as many digits as possible, or at least there can be a toggle to use BigInt globally. JSON strings are used in so many places that limiting numbers to safe integer "9007199254740991" does not make much sense.

I kind of hope this extension can be a nice json visualization tool, rather than limiting itself to the JS language standards.

**Comment by belaviyo** [comment]
I still don't understand. The extension uses BigInt when JavaScript cannot handle the number and uses a regular number otherwise. This means we are not restricted by JavaScript's numerical limitations.

**Comment by HanYaodong** [comment]
try this: `{"test": 1805072008376143872}`.
Switching between tree/code/text will make the number loose the last few digits.
![image](https://github.com/belaviyo/json-beautifier/assets/31091101/d6d4dbaa-86cf-4d55-bbdc-d41c34df6043)

**Comment by belaviyo** [comment]
By switching to `vanilla-jsoneditor` instead of `jsoneditor` the BigInt supports improves. Pleases wait for `0.5.1` release and reopen if you still have the issue.

**Comment by HanYaodong** [comment]
Cool!
