### ISSUE TITLE
EvalError

### ISSUE THREAD

**Issue by ugurhangul** [belaviyo/json-beautifier#22]
When trying to transform json gives an error 

"EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"."

![image](https://github.com/user-attachments/assets/dc2164b3-d6d4-41f3-8b20-1392f3fdd1e8)

**Comment by belaviyo** [comment]
Should be fixed by the next release. Thanks for the report.
