### ISSUE TITLE
keep expanded structure when refreshing the page

### ISSUE THREAD

**Issue by richo67** [belaviyo/json-beautifier#7]
Hi,
I was wondering if there would be possibility to keep partially or fully expanded JSON structure (as one does manually) after the page is refreshed?
Often it is useful to see which values has changed with new data fetched. 
Something like freezing the expansion status.

**Comment by richo67** [comment]
Does this means it is implemented in the latest change?

**Comment by richo67** [comment]
Hi, one more question: I am using opera and your plugin there is in version 0.1.9, will you be updating it there? Thanks.

**Comment by belaviyo** [comment]
I already submiited to Opera add-ons. But the review is very slow. Use the Chrome Store version instead.
