### ISSUE TITLE
Chinese Garbled

### ISSUE THREAD

**Issue by mlrsyz** [belaviyo/json-beautifier#9]
在浏览器插件内置页面会中文乱码
The built-in page of the browser plug-in will be garbled in Chinese
![image](https://user-images.githubusercontent.com/44489042/124906224-68ae7500-e019-11eb-805c-fcdeaa9894d7.png)
![image](https://user-images.githubusercontent.com/44489042/124906343-8da2e800-e019-11eb-8d39-24c579ebcadc.png)

**Comment by mlrsyz** [comment]
![image](https://user-images.githubusercontent.com/44489042/124907491-d018f480-e01a-11eb-9a3a-094ee8b3000d.png)
选择中文会乱码,英语则不会,可以修复吗?
Choosing Chinese will cause garbled characters, but English will not. Can it be fixed?

**Comment by belaviyo** [comment]
Should be fixed by 0.3.0 release. Thanks for the report.
